apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-envoy
  labels:
    service: front-envoy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: front-envoy
    spec:
      containers:
      - name: envoy-sidecar
        image: viswanathct/envoy-sidecar
        command: ['/usr/local/bin/envoy']
        args: ['-c', '/app/envoy-config.yaml', '--service-cluster', 'front-proxy', '-l', 'debug']
        resources: {}
        volumeMounts:
        - name: envoy-config-front-envoy
          mountPath: /app
      restartPolicy: Always
      volumes:
      - name: envoy-config-front-envoy
        configMap:
          name: envoy-config-front-envoy
          items:
            - key: config
              path: envoy-config.yaml
status: {}
