---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: p-grpc-wrapper-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/probe
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p-grpc-wrapper-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p-grpc-wrapper
  labels:
    service: p-grpc-wrapper
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: p-grpc-wrapper
    spec:
      containers:
      - name: p-grpc-wrapper
        image: viswanathct/grpc-wrapper
        command: ['/bin/sh']
        args: ['-c', 'touch /etc/probe/service.log; tail -f /etc/probe/service.log']
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - name: p-grpc-wrapper-pv-storage
            mountPath: /etc/probe
      - name: envoy-sidecar
        image: viswanathct/envoy-sidecar
        command: ['/bin/sh']
        args: ['-c', 'touch /etc/probe/envoy.log; tail -f /etc/probe/envoy.log']
        volumeMounts:
          - name: p-grpc-wrapper-pv-storage
            mountPath: /etc/probe
      restartPolicy: Always
      volumes:
      - name: p-grpc-wrapper-pv-storage
        persistentVolumeClaim:
          claimName: p-grpc-wrapper-pv-claim
status: {}
