---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: p-grpc-wrapper-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /probe
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p-grpc-wrapper-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p-grpc-wrapper
  labels:
    service: p-grpc-wrapper
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: p-grpc-wrapper
    spec:
      containers:
      - name: p-grpc-wrapper
        image: viswanathct/grpc-wrapper
        command: ['/bin/sh']
        args: ['-c', 'touch /probe/service.log; tail -f /probe/service.log']
        volumeMounts:
          - name: p-grpc-wrapper-pv-storage
            mountPath: /probe
      - name: envoy-sidecar
        image: viswanathct/envoy-sidecar
        command: ['/bin/sh']
        args: ['-c', 'touch /probe/envoy.log; tail -f /probe/envoy.log']
        volumeMounts:
          - name: p-grpc-wrapper-pv-storage
            mountPath: /probe
      restartPolicy: Always
      volumes:
      - name: p-grpc-wrapper-pv-storage
        persistentVolumeClaim:
          claimName: p-grpc-wrapper-pv-claim
status: {}
