apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  labels:
    service: statsd-exporter
spec:
  ports:
  - name: udp-in
    port: 8125
  - name: tcp-in
    port: 9125
  - name: prometheus-in
    port: 9102
  selector:
    service: statsd-exporter
status:
  loadBalancer: {}
