apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    service: zipkin
spec:
  ports:
  - name: "9411"
    port: 9411
    targetPort: 9411
  selector:
    service: zipkin
status:
  loadBalancer: {}
