---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: p-grpc-service-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/probe
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p-grpc-service-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p-grpc-service
  labels:
    service: p-grpc-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: p-grpc-service
    spec:
      containers:
      - name: p-grpc-service
        image: viswanathct/grpc-service
        command: ['/bin/sh']
        args: ['-c', 'touch /etc/probe/service.log; tail -f /etc/probe/service.log'] # #Note: This essentially is an ever-waiting process. Hence, the container will live, even when the real-process is started.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - name: p-grpc-service-pv-storage
            mountPath: /etc/probe # #Note: GCE doesn't allow mount path to be at the root.
      - name: envoy-sidecar
        image: viswanathct/envoy-sidecar
        command: ['/bin/sh']
        args: ['-c', 'touch /etc/probe/envoy.log; tail -f /etc/probe/envoy.log']
        volumeMounts:
        - name: p-grpc-service-pv-storage
          mountPath: /etc/probe
      restartPolicy: Always
      volumes:
      - name: p-grpc-service-pv-storage
        persistentVolumeClaim:
          claimName: p-grpc-service-pv-claim
status: {}
