---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: p-grpc-service-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/probe"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p-grpc-service-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p-grpc-service
  labels:
    service: p-grpc-service
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: p-grpc-service
    spec:
      containers:
      - command: ['/bin/sh']
        args: ['-c', 'touch /probe/log; tail -f /probe/log'] # #Note: This essentially is an ever-waiting service. Hence, the container will live, even when the real-process is started.
        name: p-grpc-service
        image: viswanathct/grpc-service
        resources: {}
        volumeMounts:
          - name: p-grpc-service-pv-storage
            mountPath: "/probe"
      - name: envoy-sidecar
        image: viswanathct/envoy-sidecar
        command: ['tail']
        args: ['-f', '/dev/null']
        resources: {}
        volumeMounts:
        - name: envoy-config-p-grpc-service
          mountPath: /etc
        - name: p-grpc-service-pv-storage
          mountPath: "/probe"
      restartPolicy: Always
      volumes:
      - name: p-grpc-service-pv-storage
        persistentVolumeClaim:
          claimName: p-grpc-service-pv-claim
      - name: envoy-config-p-grpc-service
        configMap:
          name: envoy-config-p-grpc-service
          items:
            - key: config
              path: envoy-config.yaml
status: {}
