apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service1-claim0
  labels:
    service: service1-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
status: {}
