apiVersion: v1
kind: Service
metadata:
  name: grpc-wrapper
  labels:
    service: grpc-wrapper
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: grpc-wrapper
status:
  loadBalancer: {}
