apiVersion: v1
kind: Service
metadata:
  name: front-envoy
  labels:
    service: front-envoy
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    service: front-envoy
status:
  loadBalancer: {}
