---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service1
  labels:
    service: service1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: service1
    spec:
      containers:
        - name: service1
          image: viswanathct/http-service
          command: ['/usr/local/bin/start_service.sh']
          env:
            - name: SERVICE_NAME
              value: "1"
          resources: {}
        - name: envoy-sidecar
          image: viswanathct/envoy-sidecar
          command: ['/usr/local/bin/envoy']
          args: ['-c', '/etc/envoy-config.yaml', '--service-cluster', 'service1'] # #Note: The service-cluster value is used as the label for the service, in the tracing reports.
          resources: {}
          volumeMounts:
            - name: service1-claim0
              mountPath: /var/logs/zipkin/service1
            - name: envoy-config-service1
              mountPath: /etc
      restartPolicy: Always
      volumes:
      - name: service1-claim0
        persistentVolumeClaim:
          claimName: service1-claim0
      - name: envoy-config-service1
        configMap:
          name: envoy-config-service1
          items:
            - key: config
              path: envoy-config.yaml
status: {}
