apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    service: service1
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: service1
status:
  loadBalancer: {}
